---
title: <center> <h1>  Attribute - Table  </h1> </center>  
# author: Aditya Kumar Mishra
output: html_document
# output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.width=12, fig.height=8,fig.align = "center",
                      out.width = "100%")
library(DBI)
library(dplyr)
library(cmap4r)
```

Attributes of a table includes:

+ name of variables 
+ type of variables, i.e., quantitative, qualitative, time, 
+ size of the table
+ space-time range information
+ numerical variable range summary


```{r  message=FALSE, warning=FALSE, echo=TRUE}
con <- dbConnect(odbc::odbc(), DSN="CMAP-MSSQL",UID="ArmLab",PWD="ArmLab2018")

## Choose table:
table.name <-  "tblsst_AVHRR_OI_NRT"


  
# Variable name in the table
tbl.fields <- dbListFields(con,table.name)
print(tbl.fields)


## collect sample data 
tbl.fields <- getDataSample(con,table.name,n=5)
print(tbl.fields) 


# Class of each column in the table
tbl.colClass <- getColClass(con,table.name)
print(tbl.colClass)


# Number of observations
nObs <- getObservationCount(con,table.name)
nObs


# Space/time information of the table
tbl.spaceTimeInfo <- getSpaceTimeRange(con,table.name)
print(tbl.spaceTimeInfo)



# Numeric variable range:
tbl.rangeNumVar <- getRangeNumVar(con,table.name)
print(tbl.rangeNumVar)
  

dbDisconnect(con)
```

