---
title: <center> <h1> Time series map </h1> </center>  
# author: Aditya Kumar Mishra
output: html_document
# output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.width=15, fig.height=7,fig.align = "center",
                      out.width = "100%")
rm(list = ls())
library(cmap4r)
library(DBI)
```

Use **getAggregatedTableData** function to download the data aggregated at a varying range of time. 

Specify following  parameters to retrieve the data from **CMAP**. 

+ Table Name (table.name)
+ Variables to be extracted (sel.var)
+ Range variable includes (latitude, longitude, depth, time)



Call **plot_ts** function to obtain **plot_ly/ggplot** object. 



## Examples I

```{r message=FALSE, warning=FALSE, echo=TRUE}
con <- dbConnect(odbc::odbc(), DSN="CMAP-MSSQL",UID="ArmLab",PWD="ArmLab2018")

# Input variable:
table.list <- c('tblSST_AVHRR_OI_NRT', 'tblAltimetry_REP', 'tblPisces_NRT')  
var.list <- c('sst', 'sla', 'NO3')   

selIndex <- 1                              # selected "sst" from the table "tblSST_AVHRR_OI_NRT"
table.name <- table.list[selIndex]
sel.var <- var.list[selIndex]   


## Example I:
range.var <- list()
range.var$lat <- c(25,30)
range.var$lon <- c(-160,-155)
range.var$time <- c('2016-03-29', '2016-05-29')


## Subset selection: data retrieval
agg.var <- 'time' 
tbl.subset <- getAggregatedTableData(con, table.name, sel.var, range.var, agg.var)
head(tbl.subset,20)   



## Plot -- Time series:
p <- plot_ts(tbl.subset,'plotly',sel.var)
p


dbDisconnect(con)
```

## Examples II

```{r message=FALSE, warning=FALSE, echo=TRUE}
con <- dbConnect(odbc::odbc(), DSN="CMAP-MSSQL",UID="ArmLab",PWD="ArmLab2018")

selIndex <- 2                               # selected "sla" from the table "tblAltimetry_REP"
table.name <- table.list[selIndex]
sel.var <- var.list[selIndex] 

## Subset selection: data retrieval
agg.var <- 'time' 
tbl.subset <- getAggregatedTableData(con, table.name, sel.var, range.var, agg.var)
head(tbl.subset,20)   


## Plot -- Time series:
p <- plot_ts(tbl.subset,'plotly',sel.var)
p

dbDisconnect(con)
```

