---
title: <center> <h1> Histogram plot </h1> </center>   
# author: Aditya Kumar Mishra
output: html_document
# output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.width=15, fig.height=7,fig.align = "center",
                      out.width = "100%")
rm(list = ls())
library(cmap4r)
library(DBI)
```


To generate a histogram plot of a variable of interest, a user needs to specify the following parameters: 

+ Table Name (table.name)
+ Variables to be extracted (sel.var)
+ Range variable includes (latitude, longitude, depth, time)

to retrieve data from **CMAP**. 

Call **plot_depth** function to obtain **plot_ly/ggplot** object. 


## Example I

```{r message=FALSE, warning=FALSE, echo=TRUE}
con <- dbConnect(odbc::odbc(), DSN="CMAP-MSSQL",UID="ArmLab",PWD="ArmLab2018")

# Inpit variable:
table.list <- c('tblSST_AVHRR_OI_NRT', 'tblArgoMerge_REP', 'tblArgoMerge_REP') 
var.list <-  c('sst', 'argo_merge_temperature_adj', 'argo_merge_salinity_adj')  

# variable "sst" selected from "tblSST_AVHRR_OI_NRT"
selIndex <- 1
table.name <- table.list[selIndex]
sel.var <- var.list[selIndex]   


# Range variable
range.var <- list()
range.var$lat <- c(20, 24)
range.var$lon <- c(-170, 150)
range.var$time <- c('2016-04-30', '2016-04-30')



# Subset selection:
tbl.subset <- getTableData(con, table.name, sel.var, range.var)
head(tbl.subset)


## Plot function available for R User
# p <- plot_hist(tbl.subset,'ggplot',sel.var)
p <- plot_hist(tbl.subset,'plotly',sel.var)
p


dbDisconnect(con)
```






