# Getting Started

## Installation

CMAP hosts data on a Microsoft SQL Server. An R user will need the following
package to connect to the database: a) “DBI”, for database interface; b) “odbc”
for connecting to the database using **DBI** interface.

But before that, for the Mac operating system, a user needs to install the
unixODBC library and database drivers. We suggest using SQL Server ODBC drivers
(Free TDS). Using Homebrew, run the following commands to install the suggested
module.


+ brew install unixodbc
+ brew install freetds


In case of Linux operating system, first, install [Anaconda
distribution](https://www.anaconda.com/distribution/#linux), and then run the
following commands to install suggested module.

+ conda install -c anaconda unixodbc
+ conda install -c anaconda freetds


Please follow the [link](https://db.rstudio.com/best-practices/drivers/) to see
other drivers available for installation.

In addition, a user may require some additional R package for downloading,
processing and visualizing the data. Run the following commands to install some
of the essential packages.

```{r eval = FALSE}
## Package "DBI" provide interface to the database
install.packages("DBI")

## Driver for the database
install.packages("odbc")

## Package for data processing:
install.packages("dbplyr")  
install.packages("plyr")

## Package for visualization:
install.packages("ggplot2")
install.packages("plotly")

```


## One useful demo

We will demonstrate the usage of this package here.

Let us say we wanted to get data from a region of the ocean.

(Picture goes here)

Then, we would use this function


Explaining the 


For any function, just do `?thisfunction` for the full set of fetures.
