# FAQ

**Q:** I get an error that looks like this:

`nanodbc/nanodbc.cpp:1587: 42000: [FreeTDS][SQL Server]Incorrect syntax near
'tblSST_AVHRR_OI_NRT'.`

**A:** This likely means the version of TDS (the connection protocol to the
database) is not of the correct version.

https://www.gitmemory.com/issue/r-dbi/odbc/209/492571028

One way you can check this is by running `tsql -C` and seeing whether the TDS
version is lower than 7.0. If it is lower than 7.0, then you can manually set it
using the environmental variable `TDSVER`. We recommend adding the line
`TDSVER=8.0` in the file `/etc/environment`, to permanently set the
environmental variable system-wide.

Some useful discussions:
1. https://github.com/r-dbi/odbc/issues/209
2. https://stackoverflow.com/questions/13066716/freetds-not-using-its-config?rq=1
3. Examples 3.6-3.8 in https://www.freetds.org/userguide/confirminstall.htm
  Basically, this shows at that the right TDS version needs to be used,
  otherwise the server will complain, with a message such as "There was a
  problem connecting to the server." You might be able to set the environment
  variable `TDSVER` in order to bypass this. For instance, in your .bashrc or your 
4. Even more useful is this: https://www.freetds.org/userguide/envvar.htm It
   tells you exactly what TDSVER does and how FreeTDS uses it.
5. You can also set the versin of TDS in your settings file `odbc.ini`, by
  adding the line "[CMAP-MSSQL] TDS_Version = 8.0". However, this won't take
  effect unless you are using the option `DSN=CMAP-MSSQL` in
  `DBI::dbConnect()`."


**Q:** My ODBC and FreeTDS setup doesn't work. (Obsolete, once `connect_cmap()`
is fully tested.)

**A:** If you set up the DSN files (the odbc.ini file and odbcinst.ini file,
both located in /etc/odbc.ini or /opt/local/etc/odbc.ini) as directed, it should
initiate a connection correctly. One possibility is that there are local DSN
files in your home directory (~/.odbc.inst and ~/.odbcinst.ini). Your database
connection will check for these files first. If these exist, either delete them
or modify these as instructed, and use these as your primary DSN files.

A bit more about ODBC and ODBCINST:
1. Basically, we need to modify the ~ODBCINST.INI~ and ~ODBC.INI~ files to
   contain information about the CMAP database, in order to connect to it.
2. The system file ~odbcinst.ini~ contains information about ODBC drivers
   available to all users, and
3. The ~odbc.ini~ file contains information about DSN's available to all users.
4. In short, ~odbcinst.ini~ defines driver options, while ~odbc.ini~ defines
connection options. ~ODBCINST.INI~ should contain a pointer:

```{}
[FreeTDS]
Description=FreeTDS Driver for MSSQL (unix users)
Driver=/usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so
Setup=/usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so
UsageCount=1
```

Your ODBCINST.INI should contain the driver to use i.e. `Driver = FreeTDS`, and
optionally the credentials to connecting to the server (the server address, the
UID and PWD, and Port). You can also specify these at run time, in your R
script.
